export const fieldItems = {
  page: {
    about: { id: "about", href: "#about" },
    skills: { id: "skills", href: "#skills" },
    projects: { id: "projects", href: "#projects" },
    certificate: { id: "certificate", href: "#certificate" },
    experience: { id: "experience", href: "#experience" },
    education: { id: "education", href: "#education" },
  },
};

export const skill = {
  nextjs: { label: "Next.js", icon: "/icon/nextjs.svg" },
  nodejs: { label: "Node.js", icon: "/icon/nodejs.svg" },
  expressjs: { label: "Express.js", icon: "/icon/expressjs.svg" },
  auth0: { label: "Next Auth", icon: "/icon/auth0.svg" },
  prisma: { label: "Prisma ORM", icon: "/icon/prisma.svg" },
  postgresql: { label: "PostgreSQL", icon: "/icon/postgresql.svg" },
  mongodb: { label: "MongoDB", icon: "/icon/mongodb.svg" },
  html: { label: "HTML", icon: "/icon/html.svg" },
  css: { label: "CSS", icon: "/icon/css.svg" },
  javascript: { label: "JavaScript", icon: "/icon/javascript.svg" },
  typescript: { label: "TypeScript", icon: "/icon/typescript.svg" },
  zod: { label: "Zod", icon: "/icon/zod.svg" },
  react: { label: "React", icon: "/icon/react.svg" },
  reactHookForm: {
    label: "React Hook Form",
    icon: "/icon/react-hook-form.svg",
  },
  shadcnUi: { label: "Shadcn UI", icon: "/icon/shadcnUi.svg" },
  tailwindCss: { label: "Tailwind CSS", icon: "/icon/tailwindCss.svg" },
  daisyUi: { label: "Daisy UI", icon: "/icon/daisyUi.svg" },
  zustand: { label: "Zustand", icon: "/icon/zustand.svg" },
  vite: { label: "Vite", icon: "/icon/vite.svg" },
  antd: { label: "Ant Design", icon: "/icon/antd.svg" },
  vercel: { label: "Vercel", icon: "/icon/vercel.svg" },
  github: { label: "Github", icon: "/icon/github.svg" },
  jwt: { label: "JSON Web Tokens", icon: "/icon/jwt.svg" },
  figma: { label: "Figma", icon: "/icon/figma.svg" },
};
